spring.datasource.url=jdbc:postgresql://dpg-d9feq7hkh4rs73cb2ul0-a.virginia-postgres.render.com:5432/smartpods_db

spring.datasource.username=smartpods_db_user

spring.datasource.password=gIGZHAAalxWrRsfWDxCjDD5YtZOBLJCi

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect